[package]
name = "day04_2022"
version = "0.1.0"
authors = ["Oliver Piorun <Oliver.Piorun@ruhr-uni-bochum.de>"]
edition = "2021"

# See more keys and their definitions at https://doc.rust-lang.org/cargo/reference/manifest.html

[dependencies]
atoi = "2.0.0"
memchr = "2.5.0"